# Generated by Django 6.0.6 on 2026-09-19 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_sellerapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerPayoutProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=150)),
                ('bank_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=34)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('upi_id', models.CharField(blank=True, max_length=120)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
