from django.urls import path
from . import views

urlpatterns = [
    path(
        "products/",
        views.product_list,
        name="product_list"
    ),
    path(
        "products/<slug:slug>/",
        views.product_detail,
        name="product_detail"
    ),
    path(
        "seller/dashboard/",
        views.seller_dashboard,
        name="seller_dashboard"
    ),
    path(
        "seller/products/",
        views.seller_products,
        name="seller_products"
    ),
    path(
        "seller/product/add/",
        views.add_product,
        name="add_product"
    ),
    path(
        "seller/import-csv/",
        views.seller_csv_import,
        name="seller_csv_import"
    ),
    path(
        "seller/inventory/",
        views.seller_inventory,
        name="seller_inventory"
    ),
    path(
        "seller/inventory/update/<int:product_id>/",
        views.update_stock,
        name="update_stock"
    ),
    path(
        "seller/product/edit/<int:product_id>/",
        views.edit_product,
        name="edit_product"
    ),
    path(
        "seller/product/delete/<int:product_id>/",
        views.delete_product,
        name="delete_product"
    ),
    path(
        "seller/reviews/",
        views.seller_reviews,
        name="seller_reviews"
    ),
]