# Generated by Django 6.0.6 on 2026-07-28 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_cancelled_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='selling_price',
        ),
    ]
